create function   [dbo].[f_GetPy](@str   nvarchar(4000)) 
returns   nvarchar(4000) 
as 
begin 
declare   @strlen   int,@re   nvarchar(4000) 
declare   @t   table(chr   nchar(1)   collate   Chinese_PRC_CI_AS,letter   nchar(1)) 
insert   into   @t(chr,letter) 
    select   'ß¹ ', 'A '   union   all   select   '°Ë ', 'B '   union   all 
    select   'àê ', 'C '   union   all   select   '…ö ', 'D '   union   all 
    select   'ŠŠ ', 'E '   union   all   select   '·¢ ', 'F '   union   all 
    select   'ê¸ ', 'G '   union   all   select   'îþ ', 'H '   union   all 
    select   'Ø¢ ', 'J '   union   all   select   'ßÇ ', 'K '   union   all 
    select   'À¬ ', 'L '   union   all   select   '‡` ', 'M '   union   all 
    select   '’‚ ', 'N '   union   all   select   'àÞ ', 'O '   union   all 
    select   'Šr ', 'P '   union   all   select   'Æß ', 'Q '   union   all 
    select   '…ß ', 'R '   union   all   select   'Øí ', 'S '   union   all 
    select   'Ëû ', 'T '   union   all   select   'ŒÜ ', 'W '   union   all 
    select   'Ï¦ ', 'X '   union   all   select   'Ñ¾ ', 'Y '   union   all 
    select   'Ž‰ ', 'Z ' 
    select   @strlen=len(@str),@re= ' ' 
    while   @strlen> 0 
    begin 
        select   top   1   @re=letter+@re,@strlen=@strlen-1 
            from   @t   a   where   chr <=substring(@str,@strlen,1) 
            order   by   chr   desc 
        if   @@rowcount=0 
            select   @re=substring(@str,@strlen,1)+@re,@strlen=@strlen-1 
    end 
    return(@re) 
end 
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
create function [dbo].[f_GetP](@str varchar(100))
returns varchar(8000)
as
begin
declare @return varchar(8000)
--Éú³ÉÁÙÊ±±í
declare @tb table(chr nchar(1) collate Chinese_PRC_CS_AS_KS_WS,py nvarchar(20)) 
insert into @tb select'ß¹','a' 
insert into @tb select'…','aes' 
insert into @tb select'°¥','ai' 
insert into @tb select'°²','an' 
insert into @tb select'°¹','ang' 
insert into @tb select'°¼','ao' 
insert into @tb select'°Ë','ba' 
insert into @tb select'’“','bai' 
insert into @tb select'ƒÄ','baike' 
insert into @tb select'®B','baiwa' 
insert into @tb select'°â','ban' 
insert into @tb select'°î','bang' 
insert into @tb select'Ùè','bao' 
insert into @tb select'È`','be' 
insert into @tb select'Úé','bei' 
insert into @tb select'±¼','ben' 
insert into @tb select'È','beng' 
insert into @tb select'°n','bi' 
insert into @tb select'±ß','bian' 
insert into @tb select'Þm','uu' 
insert into @tb select'ìá','biao' 
insert into @tb select'±ï','bie' 
insert into @tb select'šñ','bin' 
insert into @tb select'Ùû','bing' 
insert into @tb select'°h','bo' 
insert into @tb select'm','bu' 
insert into @tb select'àê','ca' 
insert into @tb select'‚Æ','cai' 
insert into @tb select'k','cal' 
insert into @tb select'²Î','can' 
insert into @tb select'²Ö','cang' 
insert into @tb select'“Ù','cao' 
insert into @tb select'ƒÔ','ce' 
insert into @tb select'Ä~','cen' 
insert into @tb select'àá','ceng' 
insert into @tb select'³€','ceok' 
insert into @tb select'K','ceom' 
insert into @tb select'ªe','ceon' 
insert into @tb select'u','ceor' 
insert into @tb select'²æ','cha' 
insert into @tb select' å','chai' 
insert into @tb select'Þ{','chan' 
insert into @tb select'Øö','chang' 
insert into @tb select'³­','chao' 
insert into @tb select'³µ','che' 
insert into @tb select'ÞÓ','chen' 
insert into @tb select'êp','cheng' 
insert into @tb select'³Ô','chi' 
insert into @tb select'³ä','chong' 
insert into @tb select'³é','chou' 
insert into @tb select'³ö','chu' 
insert into @tb select'Äu','chuai' 
insert into @tb select'çÝ','chuan' 
insert into @tb select'„V','chuang' 
insert into @tb select'´µ','chui' 
insert into @tb select'•I','chun' 
insert into @tb select'õÖ','chuo' 
insert into @tb select'ßÚ','ci' 
insert into @tb select'†ï','cis' 
insert into @tb select'´Ó','cong' 
insert into @tb select'´Õ','cou' 
insert into @tb select'´Ö','cu' 
insert into @tb select'Ùà','cuan' 
insert into @tb select'´Þ','cui' 
insert into @tb select'ß—','cun' 
insert into @tb select'¬›','cuo' 
insert into @tb select'´é','chua' 
insert into @tb select'…ö','da' 
insert into @tb select'ß¾','dai' 
insert into @tb select'µ¤','dan' 
insert into @tb select'µ±','dang' 
insert into @tb select'µ¶','dao' 
insert into @tb select'z','de' 
insert into @tb select'“g','dem' 
insert into @tb select'’O','den' 
insert into @tb select'µÆ','deng' 
insert into @tb select'ª','di' 
insert into @tb select'àÇ','dia' 
insert into @tb select'”“','dian' 
insert into @tb select'µó','diao' 
insert into @tb select'µù','die' 
insert into @tb select'†O','dei' 
insert into @tb select'‡Ã','dim' 
insert into @tb select'¶¡','ding' 
insert into @tb select'G','diu' 
insert into @tb select'¶«','dong' 
insert into @tb select'…Ê','dou' 
insert into @tb select'„†','du' 
insert into @tb select'ÂZ','duan' 
insert into @tb select'…¶','dug' 
insert into @tb select'ˆŒ','dui' 
insert into @tb select'¶Ö','dun' 
insert into @tb select'ßÍ','duo' 
insert into @tb select'ŠŠ','e' 
insert into @tb select'ŠC','en' 
insert into @tb select'íE','eng' 
insert into @tb select'˜','eo' 
insert into @tb select's','eol' 
insert into @tb select'”ñ','eos' 
insert into @tb select'¶ù','er' 
insert into @tb select'·¢','fa' 
insert into @tb select'·«','fan' 
insert into @tb select'ØÎ','fang' 
insert into @tb select'·É','fei' 
insert into @tb select'·Ô','fen' 
insert into @tb select'·á','feng' 
insert into @tb select'­ž','fenwa' 
insert into @tb select'Ò…','fiao' 
insert into @tb select'–','fo' 
insert into @tb select'ˆ¡','fou' 
insert into @tb select'·ò','fu' 
insert into @tb select'ªg','fui' 
insert into @tb select'ê¸','ga' 
insert into @tb select'ì','gai' 
insert into @tb select'¸Ê','gan' 
insert into @tb select'¸Ô','gang' 
insert into @tb select'¸Þ','gao' 
insert into @tb select'¸ê','ge' 
insert into @tb select'¸ø','gei' 
insert into @tb select'¸ù','gen' 
insert into @tb select'¸ü','geng' 
insert into @tb select'†¯','geu' 
insert into @tb select'†Ö','gib' 
insert into @tb select'†ñ','go' 
insert into @tb select'¹¤','gong' 
insert into @tb select'ƒÀ','gongfen' 
insert into @tb select'ƒÅ','gongli' 
insert into @tb select'¹´','gou' 
insert into @tb select'¹À','gu' 
insert into @tb select'¹Ï','gua' 
insert into @tb select'¹Ô','guai' 
insert into @tb select'¹Ø','guan' 
insert into @tb select'¹â','guang' 
insert into @tb select'¹é','gui' 
insert into @tb select'Ø­','gun' 
insert into @tb select'ßÃ','guo' 
insert into @tb select'Šo','ha' 
insert into @tb select'…õ','hai' 
insert into @tb select'a','hal' 
insert into @tb select'ƒË','han' 
insert into @tb select'ôŒ','hang' 
insert into @tb select'Æ’','hao' 
insert into @tb select'ƒÁ','haoke' 
insert into @tb select'Ú­','he' 
insert into @tb select'ü\','hei' 
insert into @tb select'’‹','hen' 
insert into @tb select'ºà','heng' 
insert into @tb select'‡Ö','heui' 
insert into @tb select'Y','ho' 
insert into @tb select'b','hol' 
insert into @tb select'…·','hong' 
insert into @tb select'ýJ','hou' 
insert into @tb select'ºõ','hu' 
insert into @tb select'»¨','hua' 
insert into @tb select'»²','huai' 
insert into @tb select'»¶','huan' 
insert into @tb select'Žx','huang' 
insert into @tb select'»Ò','hui' 
insert into @tb select'»è','hun' 
insert into @tb select'…¿','huo' 
insert into @tb select'‡É','geo' 
insert into @tb select'‰þ','hwa' 
insert into @tb select'Ø¢','ji' 
insert into @tb select'¼Ó','jia' 
insert into @tb select'†í','jialun' 
insert into @tb select'ê§','jian' 
insert into @tb select'½­','jiang' 
insert into @tb select'Ü´','jiao' 
insert into @tb select'½×','jie' 
insert into @tb select'½í','jin' 
insert into @tb select'ˆi','jing' 
insert into @tb select'Øç','jiong' 
insert into @tb select'L','jiu' 
insert into @tb select'™ã','jou' 
insert into @tb select'„H','ju' 
insert into @tb select'Š¤','juan' 
insert into @tb select'àÙ','jue' 
insert into @tb select'¾ü','jun' 
insert into @tb select'ßÇ','ka' 
insert into @tb select'¿ª','kai' 
insert into @tb select'f','kal' 
insert into @tb select'¿¯','kan' 
insert into @tb select'ƒÝ','hem' 
insert into @tb select'³T','kang' 
insert into @tb select'åê','kao' 
insert into @tb select'¿À','ke' 
insert into @tb select'ÃG','ken' 
insert into @tb select'„´','keng' 
insert into @tb select'Ž|','keo' 
insert into @tb select'g','keol' 
insert into @tb select'†{','keos' 
insert into @tb select'…ž','keum' 
insert into @tb select']','ki' 
insert into @tb select'¿Õ','kong' 
insert into @tb select'W','kos' 
insert into @tb select'¿Ù','kou' 
insert into @tb select'’H','ku' 
insert into @tb select'¿ä','kua' 
insert into @tb select'Øá','kuai' 
insert into @tb select'¿í','kuan' 
insert into @tb select'¿ï','kuang' 
insert into @tb select'¿÷','kui' 
insert into @tb select'À¤','kun' 
insert into @tb select'’ˆ','kuo' 
insert into @tb select'·i','kweok' 
insert into @tb select'À¬','la' 
insert into @tb select'À´','lai' 
insert into @tb select'À¼','lan' 
insert into @tb select'à¥','lang' 
insert into @tb select'ÀÌ','lao' 
insert into @tb select'Øì','le' 
insert into @tb select'À×','lei' 
insert into @tb select'Ü¨','leng' 
insert into @tb select'†o','li' 
insert into @tb select'Á©','lia' 
insert into @tb select'‹¼','lian' 
insert into @tb select'º|','liang' 
insert into @tb select'ÜG','liao' 
insert into @tb select'š¸','lie' 
insert into @tb select'…›','lin' 
insert into @tb select'Áæ','ling' 
insert into @tb select'Áï','liu' 
insert into @tb select'®F','liwa' 
insert into @tb select'‡Þ','lo' 
insert into @tb select'Áú','long' 
insert into @tb select'Â¦','lou' 
insert into @tb select'àà','lu' 
insert into @tb select'Â¿','lv' 
insert into @tb select'Œœ','lue' 
insert into @tb select'ÂÏ','luan' 
insert into @tb select'’à','lun' 
insert into @tb select'îb','luo' 
insert into @tb select'…Þ','m' 
insert into @tb select'Âè','ma' 
insert into @tb select'ßj','hweong' 
insert into @tb select'Âñ','mai' 
insert into @tb select'ò©','man' 
insert into @tb select' ¯','mang' 
insert into @tb select'„õ','mangmi' 
insert into @tb select'Ã¨','mao' 
insert into @tb select'†x','mas' 
insert into @tb select'ŽÛ','me' 
insert into @tb select'…Ð','mei' 
insert into @tb select'—È','men' 
insert into @tb select'’ú','meng' 
insert into @tb select'Û_','meo' 
insert into @tb select'²[','mi' 
insert into @tb select'å²','mian' 
insert into @tb select'ß÷','miao' 
insert into @tb select'Ø¿','mie' 
insert into @tb select'­Ÿ','miliklanm' 
insert into @tb select'Ãñ','min' 
insert into @tb select'ƒä','lem' 
insert into @tb select'Ãû','ming' 
insert into @tb select'Ãý','miu' 
insert into @tb select'Ãþ','mo' 
insert into @tb select'i','mol' 
insert into @tb select'ßè','mou' 
insert into @tb select'Ä¸','mu' 
insert into @tb select'”æ','myeo' 
insert into @tb select'C','myeon' 
insert into @tb select'—Ò','myeong' 
insert into @tb select'’‚','na' 
insert into @tb select'ÄG','nai' 
insert into @tb select'àï','nan' 
insert into @tb select'àì','nang' 
insert into @tb select'e','keg' 
insert into @tb select'Ø«','nao' 
insert into @tb select'ðÚ','ne' 
insert into @tb select'ŠÌ','nei' 
insert into @tb select'Ÿˆ','nem' 
insert into @tb select'ÄÛ','nen' 
insert into @tb select'Ç‚','neus' 
insert into @tb select'â…','ngag' 
insert into @tb select'äG','ngai' 
insert into @tb select'†«','ngam' 
insert into @tb select'ÄÝ','ni' 
insert into @tb select'Äê','nian' 
insert into @tb select'Äï','niang' 
insert into @tb select'Üà','niao' 
insert into @tb select'Äó','nie' 
insert into @tb select'Ã€','nin' 
insert into @tb select'Äþ','ning' 
insert into @tb select'Å£','niu' 
insert into @tb select'Å©','nong' 
insert into @tb select'Á…','nou' 
insert into @tb select'Å«','nu' 
insert into @tb select'Å®','nv' 
insert into @tb select'Å±','nue' 
insert into @tb select'¯‘','nve' 
insert into @tb select'Šf','nuan' 
insert into @tb select'üQ','nun' 
insert into @tb select' \','nung' 
insert into @tb select'Å²','nuo' 
insert into @tb select'¹p','o' 
insert into @tb select'‰ñ','oes' 
insert into @tb select'j','ol' 
insert into @tb select'íM','on' 
insert into @tb select'Ú©','ou' 
insert into @tb select'Šr','pa' 
insert into @tb select'Ù½','pai' 
insert into @tb select'´s','pak' 
insert into @tb select'±e','pan' 
insert into @tb select'ÅÒ','pang' 
insert into @tb select'Å×','pao' 
insert into @tb select'ÅÞ','pei' 
insert into @tb select'­›','pen' 
insert into @tb select'„ú','peng' 
insert into @tb select'›¹','peol' 
insert into @tb select'Ž‡','phas' 
insert into @tb select'êC','phdeng' 
insert into @tb select'n','phoi' 
insert into @tb select'†Ô','phos' 
insert into @tb select'Ø§','pi' 
insert into @tb select'‡æ','pian' 
insert into @tb select'çÎ','piao' 
insert into @tb select'ë­','pie' 
insert into @tb select'Ø¯','pianpang' 
insert into @tb select'æ°','pin' 
insert into @tb select'Æ¹','ping' 
insert into @tb select'îÇ','po' 
insert into @tb select'ÆÊ','pou' 
insert into @tb select'†V','deo' 
insert into @tb select'ƒÍ','ppun' 
insert into @tb select'ÆÍ','pu' 
insert into @tb select'Æß','qi' 
insert into @tb select'Æþ','qia' 
insert into @tb select'Ç§','qian' 
insert into @tb select'Ç¼','qiang' 
insert into @tb select'ƒ¿','qianke' 
insert into @tb select'­™','qianwa' 
insert into @tb select'ÇÄ','qiao' 
insert into @tb select'Æj','qie' 
insert into @tb select'Ç×','qin' 
insert into @tb select'Ïˆ','kem' 
insert into @tb select'Çâ','qing' 
insert into @tb select'öÆ','qiong' 
insert into @tb select'Çð','qiu' 
insert into @tb select'Çú','qu' 
insert into @tb select'Þ‘','keop' 
insert into @tb select'Z','quan' 
insert into @tb select'ÉU','que' 
insert into @tb select'‰æ','qun' 
insert into @tb select'’','ra' 
insert into @tb select'‡Ý','ram' 
insert into @tb select'…ß','ran' 
insert into @tb select'·y','rang' 
insert into @tb select'Üé','rao' 
insert into @tb select'ÈÇ','re' 
insert into @tb select'ÈË','ren' 
insert into @tb select'ÈÓ','reng' 
insert into @tb select'ÈÕ','ri' 
insert into @tb select'–Ñ','rong' 
insert into @tb select'¶b','rou' 
insert into @tb select'Ž]','ru' 
insert into @tb select'“É','ruan' 
insert into @tb select'—M','rui' 
insert into @tb select'Èò','run' 
insert into @tb select'…ª','ruo' 
insert into @tb select'Øí','sa' 
insert into @tb select'–Ó','saeng' 
insert into @tb select'šº','sai' 
insert into @tb select'Ìƒ','sal' 
insert into @tb select'Èý','san' 
insert into @tb select'–ø','sang' 
insert into @tb select'’û','sao' 
insert into @tb select'É«','se' 
insert into @tb select'ÑS','sed' 
insert into @tb select'Â{','sei' 
insert into @tb select'É­','sen' 
insert into @tb select'ôO','seng' 
insert into @tb select'é~','seo' 
insert into @tb select'¿L','seon' 
insert into @tb select'É±','sha' 
insert into @tb select'É¸','shai' 
insert into @tb select'É½','shan' 
insert into @tb select'ÉË','shang' 
insert into @tb select'„','shao' 
insert into @tb select'ÉÝ','she' 
insert into @tb select'Éê','shen' 
insert into @tb select'Éý','sheng' 
insert into @tb select'Ê¬','shi' 
insert into @tb select'ƒ¾','shike' 
insert into @tb select'­—','shiwa' 
insert into @tb select'…§','shou' 
insert into @tb select'Êé','shu' 
insert into @tb select'Ë¢','shua' 
insert into @tb select'Ë¤','shuai' 
insert into @tb select'ãÅ','shuan' 
insert into @tb select'Ë«','shuang' 
insert into @tb select'Ë­','shei' 
insert into @tb select'ÃŸ','shui' 
insert into @tb select'Ë±','shun' 
insert into @tb select'†d','shuo' 
insert into @tb select'Ë¿','si' 
insert into @tb select'ÏA','so' 
insert into @tb select'r','sol' 
insert into @tb select'âì','song' 
insert into @tb select'ƒð','sou' 
insert into @tb select'ËÕ','su' 
insert into @tb select'¯i','suan' 
insert into @tb select'‰å','sui' 
insert into @tb select'Ëï','sun' 
insert into @tb select'æ¶','suo' 
insert into @tb select'Ëû','ta' 
insert into @tb select'Òk','tae' 
insert into @tb select'‡ò','tai' 
insert into @tb select'Ì®','tan' 
insert into @tb select'ï¦','tang' 
insert into @tb select'—','tao' 
insert into @tb select'®z','tap' 
insert into @tb select'ß¯','te' 
insert into @tb select'Ä†','teng' 
insert into @tb select'†z','teo' 
insert into @tb select'–Y','teul' 
insert into @tb select'ÌÞ','ti' 
insert into @tb select'Ìì','tian' 
insert into @tb select'”þ','tiao' 
insert into @tb select'G','tie' 
insert into @tb select'Ìü','ting' 
insert into @tb select'h','tol' 
insert into @tb select'‡ì','tong' 
insert into @tb select'Íµ','tou' 
insert into @tb select'Í¹','tu' 
insert into @tb select'ÍÄ','tuan' 
insert into @tb select'ÍÆ','tui' 
insert into @tb select'•H','tun' 
insert into @tb select'Ø±','tuo' 
insert into @tb select'ŒÜ','wa' 
insert into @tb select'Íá','wai' 
insert into @tb select'^','wan' 
insert into @tb select'Œ²','wang' 
insert into @tb select'Î£','wei' 
insert into @tb select'‰e','wen' 
insert into @tb select'ÎÌ','weng' 
insert into @tb select'ÎÎ','wo' 
insert into @tb select'ÎÚ','wu' 
insert into @tb select'Ï¦','xi' 
insert into @tb select'ÚÀ','ei' 
insert into @tb select'¯P','xia' 
insert into @tb select'ÏÉ','xian' 
insert into @tb select'Ïç','xiang' 
insert into @tb select'ž¼','xiao' 
insert into @tb select'Ð¨','xie' 
insert into @tb select'ÐÄ','xin' 
insert into @tb select'ÐÇ','xing' 
insert into @tb select'Ð×','xiong' 
insert into @tb select'ÐÝ','xiu' 
insert into @tb select'•B','xu' 
insert into @tb select'•R','xuan' 
insert into @tb select'¯T','xue' 
insert into @tb select'ˆ_','xun' 
insert into @tb select'Ñ¾','ya' 
insert into @tb select'ÑÊ','yan' 
insert into @tb select'™ë','eom' 
insert into @tb select'Ñë','yang' 
insert into @tb select'ßº','yao' 
insert into @tb select'Ò¬','ye' 
insert into @tb select'ÄŒ','yen' 
insert into @tb select'Ò»','yi' 
insert into @tb select'U','i' 
insert into @tb select']','yin' 
insert into @tb select'Ó¦','ying' 
insert into @tb select'Ó´','yo' 
insert into @tb select'Ó¶','yong' 
insert into @tb select'ÓÅ','you' 
insert into @tb select'ÓØ','yu' 
insert into @tb select'‡ä','yuan' 
insert into @tb select'Ô»','yue' 
insert into @tb select'ÉC','yun' 
insert into @tb select'Ž‰','za' 
insert into @tb select'žÄ','zai' 
insert into @tb select'ƒ³','zan' 
insert into @tb select' ™','zang' 
insert into @tb select'Ôâ','zao' 
insert into @tb select'†¨','ze' 
insert into @tb select'Ôô','zei' 
insert into @tb select'Ôõ','zen' 
insert into @tb select'•û','zeng' 
insert into @tb select'ß¸','zha' 
insert into @tb select'®h','gad' 
insert into @tb select'‰ã','zhai' 
insert into @tb select'Õ±','zhan' 
insert into @tb select'ÕÅ','zhang' 
insert into @tb select'îÈ','zhao' 
insert into @tb select'òØ','zhe' 
insert into @tb select'Õê','zhen' 
insert into @tb select'„J','zheng' 
insert into @tb select'Ö®','zhi' 
insert into @tb select'ÖÐ','zhong' 
insert into @tb select'ÖÝ','zhou' 
insert into @tb select'„¸','zhu' 
insert into @tb select'×¥','zhua' 
insert into @tb select'×¨','zhuan' 
insert into @tb select'×ª','zhuai' 
insert into @tb select'×±','zhuang' 
insert into @tb select'æí','zhui' 
insert into @tb select'Œd','zhun' 
insert into @tb select'×¿','zhuo' 
insert into @tb select'×Î','zi' 
insert into @tb select'†€','zo' 
insert into @tb select'×Ú','zong' 
insert into @tb select'—°','zou' 
insert into @tb select'†X','zu' 
insert into @tb select'„®','zuan' 
insert into @tb select'…‰','zui' 
insert into @tb select'×ð','zun' 
insert into @tb select'×ò','zuo' 
 
declare @strlong int 
select @strlong=len(@str),@return=''
while @strlong>0
begin   
      select top 1 @return=UPPER(substring(py,1,1) )+substring(py,2,len(py))+@return,@strlong=@strlong-1 
      from @tb a where chr<=substring(@str,@strlong,1) 
      order by chr collate Chinese_PRC_CS_AS_KS_WS desc 
      if @@rowcount=0
        select @return=substring(@str,@strlong,1)+@return,@strlong=@strlong-1
   end
return(@return)
end
-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
create proc proc_get_AI
@str varchar(10)
as
declare @flag int
declare @fla int
set @flag=(select count(*) from Area where dbo.fn_GetPy(AreaName) like '%'+@str+'%') 
set @fla=(select count(*) from Area where dbo.f_GetP(AreaName) like '%'+@str+'%')
if @flag>0
select AreaName from Area where dbo.fn_GetPy(AreaName) like '%'+@str+'%' 
else
if @fla>0
select AreaName from Area where dbo.f_GetP(AreaName) like '%'+@str+'%'
else
select AreaName from Area where AreaName like '%'+@str+'%'
--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
select * from sysobjects where xtype='U' and name like '@%'